# Basics
baseURL: /
title: Platform.sh User Documentation
author: Platform.sh
description: Platform.sh User Documentation

# Themes
theme: avocadocs

uglyurls: true
pygmentsUseClasses: true

# Language settings
languages:
  en:
    contentDir: src
    languageName: English
    weight: 10
