# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'app'

# The type key specifies the language and version for your application.
type: 'nodejs:12'

# The hooks that will be triggered when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    build: !include
      type: string
      path: build.sh
    deploy: !include
      type: string
      path: deploy.sh


# The size of the persistent disk of the application (in MB).
disk: 5120

# The configuration of the application when it is exposed to the web.
web:
    commands:
      # Run the Meilisearch server
      start: "./meilisearch/meilisearch --http-addr localhost:${PORT}"
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'public'
            passthru: true
            index: ['index.html']
            scripts: false
            allow: true
            expires: 24h
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                    expires: 4w

# Mounts for Meilisearch
mounts:
    "data.ms":
        source: local
        source_path: "datams"
    "meilisearch/output":
        source: local
        source_path: "output"
    "public/scripts/xss/dist/config":
        source: local
        source_path: "config"
