http://www.{default}/:
  type: redirect
  to: https://{default}/
http://{default}/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  upstream: app:http
  cache:
    enabled: true
  ssi:
    enabled: false
  redirects:
    paths:
      # The following were the most common paths on the old site; redirect to the
      # corresponding new page. These redirects should be safe to remove in 2017.
      "/user_guide/reference/paltform-app-yaml.html": { "to": "/configuration/app-containers.html", "code": "301", "prefix": false}
      "/user_guide/overview/configuring-project-environments.html": { "to": "/administration/web/configure-environment.html", "code": "301", "prefix": false}
      "/user_guide/using/going-live.html": { "to": "/development/going-live.html", "code": "301", "prefix": false}
      "/user_guide/using/set-up-local-development.html": { "to": "/development/local.html", "code": "301", "prefix": false}
      "/user_guide/reference/configuration-files.html": { "to": "/configuration/app-containers.html", "code": "301", "prefix": false}
      "/user_guide/use-SSH.html": { "to": "/development/ssh.html", "code": "301", "prefix": false}
      "/user_guide/overview/web-ui/configure-environments.html": { "to": "/administration/web/environments.html", "code": "301", "prefix": false}
      "/user_guide/overview/web-ui/configure-project.html": { "to": "/administration/web/configure-project.html", "code": "301", "prefix": false}
      "/user_guide/overview/cli/index.html": { "to": "/overview/cli.html", "code": "301", "prefix": false}
      "/user_guide/reference/toolstacks/php/index.html": { "to": "/languages/php.html", "code": "301", "prefix": false}
      "/user_guide/reference/environment-variables.html": { "to": "/development/environment-variables.html", "code": "301", "prefix": false}
      "/user_guide/using/index.html": { "to": "/administration/users.html", "code": "301", "prefix": false}
      "/user_guide/overview/technical-requirements.html": { "to": "/overview/tools.html", "code": "301", "prefix": false}
      "/user_guide/reference/faq/known-issues.html": { "to": "/development/faq.html", "code": "301", "prefix": false}
      "/drupal_migrate/guides/type/php/drupal/migrate/import-database.html": { "to": "/drupal7/migrating.html", "code": "301", "prefix": false}
      "/user_guide/reference/toolstacks/php/configure-php.html": { "to": "/languages/php.html", "code": "301", "prefix": false}
      "/user_guide/overview/services.html": { "to": "/configuration/services.html", "code": "301", "prefix": false}

